---
argument_specs:
  main:
    options:
      systemd_timesyncd_service_name:
        type: str
      systemd_timesyncd_configuration_file:
        type: path
      systemd_timesyncd_configuration:
        type: dict
        options:
          Time:
            type: dict
            options:
              NTP:
                type: list
                elements: str
              FallbackNTP:
                type: list
                elements: str
              RootDistanceMaxSec:
                type: str
              PollIntervalMinSec:
                type: str
              PollIntervalMaxSec:
                type: str
      systemd_timesyncd_package_name:
        type: str
      systemd_timesyncd_package_version:
        type: str
      systemd_timesyncd_package_state:
        type: str
        choices:
          - present
          - absent
