---
- name: Ensure {{ systemd_unit_name }} systemd unit
  ansible.builtin.template:
    src: unit.j2
    dest: "{{ systemd_unit_file }}"
    owner: root
    group: root
    mode: "0644"
  notify: Ensure systemd configuration is reloaded
  when:
    - systemd_unit_name
    - not systemd_unit_override_name
  register: systemd_unit_state
  become: true

- name: Ensure {{ systemd_unit_name }} systemd unit override directory
  ansible.builtin.file:
    path: "{{ systemd_unit_override_directory }}"
    owner: root
    group: root
    mode: "0644"
    state: "{{ systemd_unit_override | ternary('directory', 'absent') }}"
  notify: Ensure systemd configuration is reloaded
  when:
    - systemd_unit_name
    - systemd_unit_override_name
  become: true

- name: Ensure {{ systemd_unit_name }} systemd unit {{ systemd_unit_override_name }} override
  ansible.builtin.template:
    src: unit.j2
    dest: "{{ systemd_unit_override_file }}"
    owner: root
    group: root
    mode: "0644"
  notify: Ensure systemd configuration is reloaded
  when:
    - systemd_unit_name
    - systemd_unit_override_name
  register: systemd_unit_override_state
  become: true
