---
- name: Ensure systemd unit is absent {{ systemd_unit_name }}
  ansible.builtin.file:
    path: "{{ systemd_unit_file }}"
    state: absent
  notify: Ensure systemd configuration is reloaded
  when:
    - systemd_unit_state == "absent"
    - not systemd_unit_override_name
  become: true

- name: Ensure override for systemd unit is absent {{ systemd_unit_name }}
  ansible.builtin.file:
    path: "{{ systemd_unit_override_file }}"
    state: absent
  notify: Ensure systemd configuration is reloaded
  when:
    - systemd_unit_state == "absent"
    - systemd_unit_override_name is defined
    - systemd_unit_override_name | length > 0
  become: true

- name: Ensure systemd unit {{ systemd_unit_name }}
  ansible.builtin.template:
    src: "{{ role_path | dirname | dirname }}/templates/unit_configuration.j2"
    dest: "{{ systemd_unit_file }}"
    owner: root
    group: root
    mode: "0644"
  vars:
    systemd_configuration: "{{ systemd_unit_configuration }}"
  notify: Ensure systemd configuration is reloaded
  when:
    - systemd_unit_state == "present"
    - systemd_unit_configuration is defined
    - not systemd_unit_override_name
  register: systemd_unit_file_state
  become: true

- name: Ensure override directory for systemd unit {{ systemd_unit_name }}
  ansible.builtin.file:
    path: "{{ systemd_unit_override_directory }}"
    owner: root
    group: root
    mode: "0644"
    state: "{{ (systemd_unit_override_name is defined and systemd_unit_override_name | length > 0) | ternary('directory', 'absent') }}"
  notify: Ensure systemd configuration is reloaded
  when:
    - systemd_unit_override_name is defined
    - systemd_unit_override_name | length > 0
  become: true

- name: Ensure override for systemd unit {{ systemd_unit_name }}
  ansible.builtin.template:
    src: "{{ role_path | dirname | dirname }}/templates/unit_configuration.j2"
    dest: "{{ systemd_unit_override_file }}"
    owner: root
    group: root
    mode: "0644"
  vars:
    systemd_configuration: "{{ systemd_unit_configuration }}"
  notify: Ensure systemd configuration is reloaded
  when:
    - systemd_unit_state == "present"
    - systemd_unit_configuration is defined
    - systemd_unit_override_name is defined
    - systemd_unit_override_name | length > 0
  register: systemd_unit_override_file_state
  become: true

- name: Ensure handlers are flushed
  ansible.builtin.meta: flush_handlers
