---
argument_specs:
  main:
    options:
      systemd_oomd_service_name:
        required: true
        type: str
      systemd_oomd_configuration_file:
        required: true
        type: str
      systemd_oomd_swapusedlimit:
        type: str
      systemd_oomd_defaultmemorypressurelimit:
        type: str
      systemd_oomd_defaultmemorypressuredurationsec:
        type: str
      systemd_oomd_package_name:
        required: true
        type: str
      systemd_oomd_package_version:
        type: str
      systemd_oomd_package_state:
        type: str
        choices:
          - present
          - absent
