---
- name: Ensure systemd networkd
  tags:
    - networkd
    - systemd
    - systemd_networkd
  block:
    - name: Ensure systemd networkd facts
      ansible.builtin.import_tasks: facts.yml
    - name: Ensure systemd networkd package
      ansible.builtin.import_tasks: package.yml
    - name: Ensure systemd networkd networkd.conf
      ansible.builtin.import_tasks: networkd.conf.yml
    - name: Ensure systemd networkd configurations directory
      ansible.builtin.import_tasks: directory.yml
    - name: Ensure systemd networkd netdev configuration
      ansible.builtin.import_tasks: netdev.yml
    - name: Ensure systemd networkd network configuration
      ansible.builtin.import_tasks: network.yml
    - name: Ensure systemd networkd systemd service
      ansible.builtin.import_tasks: systemd_service.yml
