---
- name: Ensure systemd networkd netdev configuration
  ansible.builtin.template:
    src: "{{ role_path | dirname | dirname }}/templates/configuration.j2"
    dest: "{{ systemd_networkd_configurations_directory }}/{{ systemd_networkd_netdev_configuration.NetDev.Name }}.netdev"
    group: root
    owner: root
    mode: "0644"
  vars:
    systemd_configuration: "{{ systemd_networkd_netdev_configuration }}"
  loop: "{{ systemd_networkd_netdevs_configuration }}"
  loop_control:
    label: "{{ systemd_networkd_netdev_configuration.NetDev.Name }}"
    loop_var: systemd_networkd_netdev_configuration
  become: true
  register: systemd_networkd_netdev_conf
