---
- name: ensure networkd.conf
  ansible.builtin.template:
    src: networkd.conf.j2
    dest: "{{ systemd_networkd_configuration_file }}"
    group: root
    owner: root
    mode: "0644"
  become: true
  register: systemd_networkd_conf
