---
namespace: "damex"
name: "systemd"
version: "0.1.7"
readme: "README.md"
authors:
  - "Roman Kuzmitskii <damex.pp@icloud.com>"
license_file: "LICENSE"
tags:
  - "systemd"
repository: "https://github.com/damex/ansible-collections-systemd"
