---
namespace: damex
name: systemd
version: 0.2.6
readme: README.md
authors:
  - Roman Kuzmitskii <ansible@damex.org>
license_file: LICENSE
tags:
  - systemd
repository: https://github.com/damex/ansible-collections-systemd
dependencies:
  damex.apt: "*"
