---
namespace: "damex"
name: "systemd"
version: "0.2.4"
readme: "README.md"
authors:
  - "Roman Kuzmitskii <ansible@damex.org>"
dependencies:
  "damex.apt": "*"
license_file: "LICENSE"
tags:
  - "systemd"
repository: "https://github.com/damex/ansible-collections-systemd"
