---
argument_specs:
  main:
    options:
      systemd_pstore_service_name:
        type: str
      systemd_pstore_configuration_file:
        type: path
      systemd_pstore_configuration:
        type: dict
        options:
          PStore:
            type: dict
            options:
              Storage:
                type: str
                choices:
                  - none
                  - external
                  - journal
              Unlink:
                type: bool
