---
argument_specs:
  main:
    options:
      systemd_resolved_service_name:
        type: str
      systemd_resolved_configuration_file:
        type: path
      systemd_resolved_configuration:
        type: dict
        options:
          Resolve:
            type: dict
            options:
              DNS:
                type: list
                elements: str
              FallbackDNS:
                type: list
                elements: str
              Domains:
                type: list
                elements: str
              LLMNR:
                type: str
                choices:
                  - "false"
                  - "true"
                  - resolve
              MulticastDNS:
                type: str
                choices:
                  - "false"
                  - "true"
                  - resolve
              DNSSEC:
                type: str
                choices:
                  - "false"
                  - "true"
                  - allow-downgrade
              DNSOverTLS:
                type: str
                choices:
                  - "false"
                  - "true"
                  - opportunistic
              Cache:
                type: str
                choices:
                  - "false"
                  - "true"
                  - no-negative
              DNSStubListener:
                type: str
                choices:
                  - "false"
                  - "true"
                  - tcp
                  - udp
              ReadEtcHosts:
                type: bool
      systemd_resolved_package_name:
        type: str
      systemd_resolved_package_version:
        type: str
      systemd_resolved_package_state:
        type: str
        choices:
          - present
          - absent
