---
- name: Ensure systemd localed
  tags:
    - localed
    - systemd_localed
    - systemd
  block:
    - name: Ensure systemd localed locale
      ansible.builtin.import_tasks: localectl.yml
    - name: Ensure systemd localed systemd service
      ansible.builtin.import_tasks: systemd_service.yml
