---
- name: Ensure systemd journald
  tags:
    - journald
    - systemd_journald
    - systemd
  block:
    - name: Ensure systemd journald journald.conf
      ansible.builtin.import_tasks: journald.conf.yml
    - name: Ensure systemd journald systemd service
      ansible.builtin.import_tasks: systemd_service.yml
