---
systemd_resolved_service_name: systemd-resolved
systemd_resolved_configuration_file: /etc/systemd/resolved.conf
systemd_resolved_package_name: systemd-resolved
systemd_resolved_package_state: present
