---
argument_specs:
  main:
    options:
      systemd_networkd_service_name:
        type: str
      systemd_networkd_configuration_file:
        type: path
      systemd_networkd_configurations_directory:
        type: path
      systemd_networkd_package_name:
        type: str
      systemd_networkd_package_version:
        type: str
      systemd_networkd_package_state:
        type: str
        choices:
          - present
          - absent
      systemd_networkd_conf_configuration:
        type: dict
        options:
          Network:
            type: dict
            options:
              SpeedMeter:
                type: bool
              SpeedMeterIntervalSec:
                type: str
              ManageForeignRoutingPolicyRules:
                type: bool
              ManageForeignRoutes:
                type: bool
              RouteTable:
                type: str
          DHCPv4:
            type: dict
            options:
              DUIDType:
                type: str
              DUIDRawData:
                type: str
              UseDomains:
                type: str
          DHCPv6:
            type: dict
            options:
              DUIDType:
                type: str
              DUIDRawData:
                type: str
              UseDomains:
                type: str
      systemd_networkd_links_configuration:
        type: list
        elements: dict
        options:
          Match:
            type: dict
            options:
              OriginalName:
                type: str
              Path:
                type: str
              Driver:
                type: str
              Type:
                type: str
              MACAddress:
                type: str
          Link:
            type: dict
            options:
              SR-IOVVirtualFunctions:
                type: int
              MACAddress:
                type: str
              Name:
                type: str
              MTUBytes:
                type: str
              Duplex:
                type: str
                choices:
                  - half
                  - full
              WakeOnLan:
                type: str
          SR-IOV:
            type: list
            elements: dict
            options:
              VirtualFunction:
                type: int
              VLANId:
                type: int
              QualityOfService:
                type: int
              VLANProtocol:
                type: str
                choices:
                  - 802.1Q
                  - 802.1ad
              MACSpoofCheck:
                type: bool
              QueryReceiveSideScaling:
                type: bool
              Trust:
                type: bool
              LinkState:
                type: str
              MACAddress:
                type: str
      systemd_networkd_netdevs_configuration:
        type: list
        elements: dict
        options:
          NetDev:
            type: dict
            options:
              Name:
                type: str
              Kind:
                type: str
          Bond:
            type: dict
            options:
              Mode:
                type: str
              MIIMonitorSec:
                type: str
              LACPTransmitRate:
                type: str
              TransmitHashPolicy:
                type: str
      systemd_networkd_networks_configuration:
        type: list
        elements: dict
        options:
          Match:
            type: dict
            options:
              Name:
                type: str
          Network:
            type: dict
            options:
              Gateway:
                type: str
              DNS:
                type: str
              Bond:
                type: str
              LinkLocalAddressing:
                type: str
              IPv6AcceptRA:
                type: str
          Address:
            type: list
            elements: dict
            options:
              Address:
                type: str
          Route:
            type: list
            elements: dict
            options:
              Gateway:
                type: str
              Table:
                type: int
          RoutingPolicyRule:
            type: list
            elements: dict
            options:
              From:
                type: str
              Table:
                type: int
