---
- name: Ensure {{ systemd_service_name }} systemd service
  become: true
  when:
    - systemd_service_name | length
  block:
    - name: Ensure {{ systemd_service_name }} systemd service is enabled
      ansible.builtin.systemd:
        name: "{{ systemd_service_name }}"
        enabled: "{{ systemd_service_enabled }}"

    - name: Ensure {{ systemd_service_name }} systemd service is started
      ansible.builtin.systemd:
        name: "{{ systemd_service_name }}"
        state: "{{ systemd_service_state }}"

    - name: Ensure {{ systemd_service_name }} systemd service is reloaded
      ansible.builtin.systemd:
        name: "{{ systemd_service_name }}"
        state: reloaded
      when:
        - systemd_service_reload_on

    - name: Ensure {{ systemd_service_name }} systemd service is restarted
      ansible.builtin.systemd:
        name: "{{ systemd_service_name }}"
        state: restarted
      when:
        - systemd_service_restart_on
