---
- name: Ensure systemd service {{ systemd_service_name }}
  ansible.builtin.systemd:
    name: "{{ systemd_service_name }}"
    state: "{{ 'restarted' if systemd_service_restart_on else 'reloaded' if systemd_service_reload_on else systemd_service_state }}"
    masked: "{{ systemd_service_masked }}"
    enabled: "{{ systemd_service_enabled }}"
  become: true
  delegate_to: "{{ systemd_service_remote_host | default(omit) }}"
