---
- name: Get current hostnamectl hostname
  ansible.builtin.command: hostnamectl status --static
  changed_when: false
  register: systemd_hostnamed_hostnamectl_hostname

- name: Ensure hostnamectl hostname
  ansible.builtin.command: hostnamectl set-hostname {{ inventory_hostname }}
  when: inventory_hostname != systemd_hostnamed_hostnamectl_hostname.stdout
  become: true
