---
- name: Ensure systemd hostnamed
  tags:
    - hostnamed
    - systemd_hostnamed
    - systemd
  block:
    - name: Ensure systemd hostnamed hostname
      ansible.builtin.import_tasks: hostnamectl.yml
    - name: Ensure systemd hostnamed systemd service
      ansible.builtin.import_tasks: systemd_service.yml
