---
- name: ensure systemd hostnamed
  block:
    - name: ensure systemd hostnamed hostname
      ansible.builtin.import_tasks: hostnamectl.yml
    - name: ensure systemd hostnamed systemd service
      ansible.builtin.import_tasks: systemd_service.yml
  tags:
    - hostnamed
    - systemd_hostnamed
    - systemd
