---
- name: Ensure systemd service {{ systemd_hostnamed_service_name }}
  ansible.builtin.include_role:
    name: damex.systemd.systemd_service
  vars:
    systemd_service_name: "{{ systemd_hostnamed_service_name }}"
