---
- name: "ensure {{ systemd_hostnamed_service_name }} systemd service"
  include_role:
    name: "damex.systemd.systemd_service"
  vars:
    systemd_service_name: "{{ systemd_hostnamed_service_name }}"
