---
argument_specs:
  main:
    options:
      systemd_journald_service_name:
        type: str
      systemd_journald_configuration_file:
        type: path
      systemd_journald_configuration:
        type: dict
        options:
          Journal:
            type: dict
            options:
              Storage:
                type: str
                choices:
                  - volatile
                  - persistent
                  - auto
                  - none
              Compress:
                type: bool
              Seal:
                type: bool
              SplitMode:
                type: str
                choices:
                  - uid
                  - none
              RateLimitInterval:
                type: str
              RateLimitBurst:
                type: int
              SystemMaxUse:
                type: str
              SystemKeepFree:
                type: str
              SystemMaxFileSize:
                type: str
              SystemMaxFiles:
                type: int
              RuntimeMaxUse:
                type: str
              RuntimeKeepFree:
                type: str
              RuntimeMaxFileSize:
                type: str
              RuntimeMaxFiles:
                type: int
              MaxFileSec:
                type: str
              MaxRetentionSec:
                type: str
              SyncIntervalSec:
                type: str
              ForwardToSyslog:
                type: bool
              ForwardToKMsg:
                type: bool
              ForwardToConsole:
                type: bool
              ForwardToWall:
                type: bool
              ForwardToSocket:
                type: bool
              MaxLevelStore:
                type: str
                choices:
                  - emerg
                  - alert
                  - crit
                  - err
                  - warning
                  - notice
                  - info
                  - debug
              MaxLevelSyslog:
                type: str
                choices:
                  - emerg
                  - alert
                  - crit
                  - err
                  - warning
                  - notice
                  - info
                  - debug
              MaxLevelKMsg:
                type: str
                choices:
                  - emerg
                  - alert
                  - crit
                  - err
                  - warning
                  - notice
                  - info
                  - debug
              MaxLevelConsole:
                type: str
                choices:
                  - emerg
                  - alert
                  - crit
                  - err
                  - warning
                  - notice
                  - info
                  - debug
              MaxLevelWall:
                type: str
                choices:
                  - emerg
                  - alert
                  - crit
                  - err
                  - warning
                  - notice
                  - info
                  - debug
              MaxLevelSocket:
                type: str
                choices:
                  - emerg
                  - alert
                  - crit
                  - err
                  - warning
                  - notice
                  - info
                  - debug
              ReadKMsg:
                type: bool
              Audit:
                type: bool
              TTYPath:
                type: path
              LineMax:
                type: str
