---
- name: Ensure systemd oomd oomd.conf
  ansible.builtin.template:
    src: "{{ role_path | dirname | dirname }}/templates/configuration.j2"
    dest: "{{ systemd_oomd_configuration_file }}"
    group: root
    owner: root
    mode: "0644"
  vars:
    systemd_configuration: "{{ systemd_oomd_configuration }}"
  become: true
  register: systemd_oomd_conf
  when: systemd_oomd_configuration is defined
