---
- name: ensure systemd pstore
  block:
    - name: ensure systemd pstore pstore.conf
      ansible.builtin.import_tasks: pstore.conf.yml
    - name: ensure systemd pstore systemd service
      ansible.builtin.import_tasks: systemd_service.yml
  tags:
    - pstore
    - systemd_pstore
    - systemd
