---
- name: ensure {{ systemd_pstore_service_name }} systemd service
  ansible.builtin.include_role:
    name: damex.systemd.systemd_service
  vars:
    systemd_service_name: "{{ systemd_pstore_service_name }}"
    systemd_service_restart_on: "{{ systemd_pstore_conf.changed }}"
