---
- name: Ensure systemd timesyncd package
  ansible.builtin.include_role:
    name: damex.apt.apt_packages
  vars:
    apt_packages:
      - name: "{{ systemd_timesyncd_package_name }}"
        version: "{{ systemd_timesyncd_package_version }}"
        state: "{{ systemd_timesyncd_package_state }}"
