---
- name: Ensure timesyncd.conf
  ansible.builtin.template:
    src: timesyncd.conf.j2
    dest: "{{ systemd_timesyncd_configuration_file }}"
    group: root
    owner: root
    mode: "0644"
  register: systemd_timesyncd_conf
  become: true
