---
- name: Ensure systemd firewalld
  tags:
    - firewalld
    - systemd
    - systemd_firewalld
  block:
    - name: Ensure systemd firewalld facts
      ansible.builtin.import_tasks: facts.yml
    - name: Ensure systemd firewalld package
      ansible.builtin.import_tasks: package.yml
    - name: Ensure systemd firewalld systemd service
      ansible.builtin.import_tasks: systemd_service.yml
    - name: Ensure systemd firewalld zones
      ansible.builtin.import_tasks: zones.yml
    - name: Ensure systemd firewalld rules
      ansible.builtin.import_tasks: rules.yml
