---
- name: Ensure systemd firewalld rules
  ansible.posix.firewalld:
    port: "{{ systemd_firewalld_rule.port | default(omit) }}"
    protocol: "{{ systemd_firewalld_rule.protocol | default(omit) }}"
    service: "{{ systemd_firewalld_rule.service | default(omit) }}"
    immediate: "{{ systemd_firewalld_rule.immediate | default(systemd_firewalld_rule_immediate) }}"
    interface: "{{ systemd_firewalld_rule.interface | default(omit) }}"
    permanent: "{{ systemd_firewalld_rule.permanent | default(systemd_firewalld_rule_permanent) }}"
    rich_rule: "{{ systemd_firewalld_rule.rich_rule | default(omit) }}"
    zone: "{{ systemd_firewalld_rule.zone | default(systemd_firewalld_rule_zone) }}"
    source: "{{ systemd_firewalld_rule.source | default(omit) }}"
    state: "{{ systemd_firewalld_rule.state | default(systemd_firewalld_rule_state) }}"
  loop: "{{ systemd_firewalld_rules }}"
  loop_control:
    label: "{{ systemd_firewalld_rule }}"
    loop_var: systemd_firewalld_rule
  become: true
