---
- name: "ensure systemd resolved"
  block:
    - import_tasks: "environment.yml"
    - import_tasks: "resolved.conf.yml"
    - import_tasks: "systemd_service.yml"
    - import_tasks: "resolv.conf.yml"
  tags:
    - "resolved"
    - "systemd_resolved"
    - "systemd"
