---
- name: Ensure systemd resolved package
  ansible.builtin.include_role:
    name: damex.apt.apt_packages
  vars:
    apt_packages: # noqa: var-naming[no-role-prefix]
      - name: "{{ systemd_resolved_package_name }}"
        version: "{{ systemd_resolved_package_version }}"
        state: "{{ systemd_resolved_package_state }}"
