---
- name: ensure resolved.conf
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: "{{ systemd_resolved_configuration_file }}"
    group: root
    owner: root
    mode: "0644"
  become: true
  register: systemd_resolved_conf
