---
- name: Ensure resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  become: true
  when: not systemd_resolved_dnsstublistener
    and systemd_resolved_nss

- name: Ensure stub resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
  become: true
  when: systemd_resolved_dnsstublistener
    and not systemd_resolved_nss
