---
- name: Ensure {{ systemd_resolved_service_name }} systemd service
  ansible.builtin.include_role:
    name: damex.systemd.systemd_service
  vars:
    systemd_service_name: "{{ systemd_resolved_service_name }}"
    systemd_service_restart_on: "{{ systemd_resolved_conf.changed }}"
