---
name: ansible-galaxy
on: # yamllint disable-line rule:truthy
  push:
    paths:
      - galaxy.yml
    branches:
      - main

jobs:
  ansible-galaxy:
    name: ansible-galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install --user pipenv
      - run: make pipenv
      - run: pipenv run ansible-galaxy collection build
      - run: pipenv run ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} damex-digitalocean-*.tar.gz
