---
name: ansible-galaxy
on: # yamllint disable-line rule:truthy
  push:
    paths:
      - galaxy.yml
    branches:
      - main

jobs:
  ansible-galaxy:
    name: ansible-galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install ansible-core==2.14.2
      - run: ansible-galaxy collection build
      - run: ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} damex-systemd-*.tar.gz
