---
name: linting
on: # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - run: pip install --user pipenv
      - run: make pipenv
      - run: pipenv run ansible-lint
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - run: pip install --user pipenv
      - run: make pipenv
      - run: pipenv run yamllint -s .
