---
systemd_timesyncd_service_name: systemd-timesyncd
systemd_timesyncd_configuration_file: /etc/systemd/timesyncd.conf
systemd_timesyncd_package_name: systemd-timesyncd
systemd_timesyncd_package_state: present
